export const data = [
  {
    id: 1,
    name: 'Apple iPhone 11 128GB',
    company: 'Apple',
    short_desc: 'something',
    img: 'Apple_Iphone11_128.jpg',
    threads_name: 'Apple A13 Bionic',
    front_camera: '12MP',
    main_camera: '12MP',
    count: 1,
    quantity_threads: 6,
    memory: 128,
    price: 10000,
    click: false,
    click_versus: false,
  },
  {
    id: 2,
    name: 'Apple iPhone 13 128GB',
    company: 'Apple',
    short_desc: 'something',
    img: 'Apple_Iphone13_128.jpg',
    threads_name: 'Apple A14 Bionic',
    front_camera: '12MP',
    main_camera: '12MP',
    price: 15000,
    count: 1,
    quantity_threads: 6,
    memory: 128,
    click: false,
    click_versus: false,
  },
];
